#!/bin/bash
# Mydroid is a Linux frontend to manage your Android device

source api

main() {
    if [[ "$(phone_connection_state)" != "Connected" ]]; then
        yad --width=400 --title="Mydroid" --center \
            --text "No Android phone detected.\n\nIf your phone is connected, you might need to enable USB Debugging in Developer Options"
        exit 0
    fi

    if [[ "$(is_dex_supported)" == "Yes" ]]; then
        yadbuttons=("--field=Samsung DeX!video-display:FBTN" "bash -c 'samsung_dex'")
    elif [[ "$(is_dex_supported)" == "Partially" ]]; then
        yadbuttons=("--field=Desktop UI (DeX-like)!video-display:FBTN" "bash -c 'samsung_dex'")
    else
        yadbuttons=()
    fi


    model=$(phone_type)
    device_name=$(get_device_name)
    yad --form --window-icon="phone" --image="phone" --image-on-top --center --no-buttons \
        --title="$device_name" --width=300 --height=200 --text="<big><b>$device_name</b></big>\n$model" \
        --columns=1 --borders=10 \
        --field=":LBL" "" --field="<big><b>Quick Options</b></big>:LBL" "" \
        --field="Browse Files!media-flash":FBTN "bash -c 'open_mtp_device'" \
        --field="Screen Mirror!phone":FBTN "bash -c 'screen_mirror'" \
        "${yadbuttons[@]}" \
        --field=":LBL" "" --field="<big><b>Network Options</b></big>:LBL" "" \
        --field="SIM Card Information!network-vpn":FBTN "bash -c 'sim_info_gui'" \
        --field="Enable/Disable USB Tethering!network-wired":FBTN "bash -c 'enable_usb_tethering'" \
        --field=":LBL" "" --field="<big><b>Advanced</b></big>:LBL" "" \
        --field="Import APK!mail-send-receive":FBTN "bash -c 'import_apk'" \
        --field="List installed apps!applications-other":FBTN "bash -c 'list_packages'" \
        --field="About Phone!system-help":FBTN "bash -c 'phone_info'"
}

main