#!/bin/bash
# Mydroid is a Linux frontend to manage your Android device

source api

main() {
    if [[ "$(phone_connection_state)" != "Connected" ]]; then
        yad --width=400 --title="Mydroid" --center \
            --text "No Android phone detected.\n\nIf your phone is connected, you might need to enable USB Debugging in Developer Options"
        exit 0
    fi

    model=$(phone_type)
    device_name=$(get_device_name)
    yad --form --window-icon="phone" --image="phone" --image-on-top --center --no-buttons --homogeneous \
        --title="$device_name" --width=300 --height=400 --text="<big><b>$device_name</b></big>\n$model" \
        --columns=1 --borders=10 \
        --field=":LBL" "" --field="<big><b>Quick Options</b></big>:LBL" "" \
        --field="Screen Mirror!phone":FBTN "bash -c 'screen_mirror'" \
        --field=":LBL" "" --field="<big><b>Network Options</b></big>:LBL" "" \
        --field="SIM Card Information!network-vpn":FBTN "bash -c 'sim_info_gui'" \
        --field="Enable/Disable USB Tethering!network-wired":FBTN "bash -c 'enable_usb_tethering'"
}

main